In [7]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# read in pickle files to dataframes
imdb_df = pd.read_pickle("imdb_df.pkl")
oscar_df = pd.read_pickle("oscar_df.pkl")

# join datasets together by film id
# imdb is id; oscar is FilmId
merged_df = pd.merge(oscar_df, imdb_df, left_on='FilmId', right_on='id', how='left', indicator=True)
merged_df = merged_df.drop(columns=['id'])
merged_df.head(10)

,Ceremony,Year,Class,CanonicalCategory,Category,Film,FilmId,Name,Nominees,Winner,...,budget,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,production_companies,genres,languages,_merge
0,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Noose,tt0019217,Richard Barthelmess,Richard Barthelmess,NaN,...,<NA>,<NA>,<NA>,<NA>,1928-01-29,[United States],[First National Pictures],[Drama],"[None, English]",both
1,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Patent Leather Kid,tt0018253,Richard Barthelmess,Richard Barthelmess,NaN,...,<NA>,<NA>,<NA>,<NA>,1927-09-01,[United States],[First National Pictures],"[Boxing, Drama, Romance, Sport, War]","[None, English]",both
2,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Last Command,tt0019071,Emil Jannings,Emil Jannings,True,...,<NA>,<NA>,<NA>,<NA>,1928-01-21,[United States],[Paramount Pictures],"[Political Drama, Showbiz Drama, Tragedy, Trag...","[None, English]",both
3,1,1927/28,Acting,ACTOR IN A LEADING ROLE,ACTOR,The Way of All Flesh,tt0019553,Emil Jannings,Emil Jannings,True,...,<NA>,<NA>,<NA>,859900,1927-10-01,[United States],[Paramount Pictures],[Drama],"[None, English]",both
4,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,A Ship Comes In,tt0018389,Louise Dresser,Louise Dresser,NaN,...,<NA>,<NA>,<NA>,<NA>,1928-06-04,[United States],[DeMille Pictures Corporation],[Drama],[None],both
5,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,7th Heaven,tt0018379,Janet Gaynor,Janet Gaynor,True,...,1300000,<NA>,<NA>,<NA>,1927-10-30,[United States],"[Frank Borzage Production, Fox Film Corporation]","[Drama, Romance]","[None, English]",both
6,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Street Angel,tt0019429,Janet Gaynor,Janet Gaynor,True,...,<NA>,<NA>,<NA>,3706000,1928-08-19,[United States],[Fox Film Corporation],[Drama],"[None, English]",both
7,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Sunrise,tt0018455,Janet Gaynor,Janet Gaynor,True,...,200000,<NA>,121848,<NA>,1927-11-04,[United States],[Fox Film Corporation],"[Dark Romance, Psychological Drama, Drama, Rom...","[None, English]",both
8,1,1927/28,Acting,ACTRESS IN A LEADING ROLE,ACTRESS,Sadie Thompson,tt0019344,Gloria Swanson,Gloria Swanson,NaN,...,650000,<NA>,<NA>,<NA>,1928-01-07,[United States],[Gloria Swanson Pictures],[Drama],[English],both
9,1,1927/28,Production,ART DIRECTION,ART DIRECTION,Sunrise,tt0018455,Rochus Gliese,Rochus Gliese,NaN,...,200000,<NA>,121848,<NA>,1927-11-04,[United States],[Fox Film Corporation],"[Dark Romance, Psychological Drama, Drama, Rom...","[None, English]",both

In [3]:
# here we want to see a list of join failures, i.e. oscar nominees missing from the imdb dataset
not_joined = (
    merged_df
    .loc[merged_df['_merge'] == 'left_only']
    .groupby('Category')
    .size()
    .sort_values(ascending=False)
)

not_joined

Category
FOREIGN LANGUAGE FILM                                  21
MUSIC (Original Song)                                   8
CINEMATOGRAPHY                                          5
COSTUME DESIGN                                          3
MUSIC (Song--Original for the Picture)                  3
MUSIC (Scoring of a Musical Picture)                    3
ANIMATED FEATURE FILM                                   3
MUSIC (Song)                                            3
SPECIAL AWARD                                           3
WRITING (Adapted Screenplay)                            2
DIRECTING                                               2
INTERNATIONAL FEATURE FILM                              2
ART DIRECTION                                           2
ACTRESS IN A SUPPORTING ROLE                            2
ACTOR                                                   1
HONORARY AWARD                                          1
FILM EDITING                                            1
BEST PICTURE                                            1
AWARD OF COMMENDATION                                   1
ACTRESS IN A LEADING ROLE                               1
ACTOR IN A LEADING ROLE                                 1
MUSIC (Scoring: Adaptation and Original Song Score)     1
MUSIC (Original Score)                                  1
PRODUCTION DESIGN                                       1
OUTSTANDING PICTURE                                     1
SOUND MIXING                                            1
SOUND EDITING                                           1
SOUND RECORDING                                         1
WRITING                                                 1
WRITING (Original Screenplay)                           1
WRITING (Screenplay--Original)                          1
dtype: int64

In [4]:
# total join failures
print(not_joined.sum())

79

In [5]:
# create a dataframe with movies in imdb dataset that were not nominated for oscars
non_oscar_noms = imdb_df[~imdb_df['id'].isin(oscar_df['FilmId'])]
non_oscar_noms.head()

,id,title,rating,votes,meta_score,writers,directors,stars,budget,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,production_companies,genres,languages
0,tt0011370,Klostret i Sendomir,6.9,485,<NA>,"[Franz Grillparzer, Victor Sjöström]",[Victor Sjöström],"[Tore Svennberg, Tora Teje, Richard Lund, René...",<NA>,<NA>,<NA>,<NA>,1920-01-01,[Sweden],[Svenska Biografteatern AB],[Drama],[None]
1,tt0011413,The Lost City,4.7,35,<NA>,[Frederick Chapin],[E.A. Martin],"[Juanita Hansen, George Chesebro, Frank Clark,...",<NA>,<NA>,<NA>,<NA>,1920-01-01,[United States],[Selig Polyscope Company],"[Action, Adventure]","[None, English]"
2,tt0276209,Hypnose,7.0,19,<NA>,[Karl Schneider],[Richard Eichberg],"[Lee Parry, Gertrud de Lalsky, Karl Halden, Be...",<NA>,<NA>,<NA>,<NA>,1920-01-03,[Germany],[Richard Eichberg-Film GmbH],"[Drama, Mystery]",[None]
3,tt0010495,My Husband's Other Wife,5.3,17,<NA>,[Stanley Olmstead],[J. Stuart Blackton],"[Sylvia Breamer, Robert Gordon, Warren Chandle...",<NA>,<NA>,<NA>,<NA>,1920-01-04,[United States],[J. Stuart Blackton Feature Pictures],"[Drama, Romance]",[None]
4,tt0010502,Nachtgestalten,5.6,25,<NA>,"[Richard Oswald, Karl Hans Strobl]",[Richard Oswald],"[Paul Wegener, Reinhold Schünzel, Erna Morena,...",<NA>,<NA>,<NA>,<NA>,1920-01-09,[Germany],[Richard-Oswald-Produktion],[Horror],"[None, German]"

In [6]:
non_oscar_noms.shape

(55684, 17)